algo = input('Digite algo: ')
print(f'{algo} é do tipo {type(algo)}')
print(f'{algo} é um número? {algo.isnumeric()}')
print(f'{algo} é alphabetico? {algo.isalpha()}')
print(f'{algo} é alphanumerico? {algo.isalnum()}')
print(f'{algo} esta todo em minusculo? {algo.islower()}')
print(f'{algo} esta todo em maiusculo? {algo.isupper()}')
print(f'{algo} está capitalizada? {algo.istitle()}')
print(f'{algo} só tem espaço? {algo.isspace()}')
